### ISSUE TITLE
Discovery Perks link does not work on Drinks page

### ISSUE THREAD

**Issue by PanicoLV** [BlakeAlvarez/DiscoFood#12]
![DRINK PAGE](https://user-images.githubusercontent.com/98421273/158293115-a1a07850-aa4e-4d77-ad30-19a2940c8ee6.jpg)
![DRINK HOME ERROR](https://user-images.githubusercontent.com/98421273/158293131-c3e662cb-1c03-4611-9c5d-f3ec041396fc.png)

**Comment by dannyhabash321** [comment]
fixed
