### ISSUE TITLE
Discovery Perks link does not work on food page

### ISSUE THREAD

**Issue by PanicoLV** [BlakeAlvarez/DiscoFood#13]
![FOOD PAGE](https://user-images.githubusercontent.com/98421273/158293199-ef517862-7415-4700-bef6-738bcf32a8c3.jpg)
![DRINK HOME ERROR](https://user-images.githubusercontent.com/98421273/158293212-c58bc174-679a-46e6-bb5b-fe9f271efd2e.png)

**Comment by BlakeAlvarez** [comment]
solved :)
